# Generated by Django 2.2.5 on 2020-07-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200707_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.CharField(default='', max_length=200),
        ),
    ]
