# Generated by Django 2.2.5 on 2020-07-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200707_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.FileField(default='/Users/tarcher/Desktop/dummy.pdf', upload_to='resumes_files'),
        ),
    ]
