# Generated by Django 2.2.5 on 2020-07-08 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200708_0212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='resume_file',
            new_name='resume',
        ),
    ]
