# Generated by Django 2.2.5 on 2020-07-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200710_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='removed_count',
            field=models.IntegerField(default=0),
        ),
    ]
