# Generated by Django 2.2.5 on 2020-07-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profile_removed_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='queries_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='query_limit',
            field=models.IntegerField(default=10),
        ),
    ]
