# Generated by Django 2.2.5 on 2020-07-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0028_remove_jobpost_applied_users'),
        ('users', '0015_auto_20200718_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='applied_posts',
            field=models.ManyToManyField(blank=True, to='jobsapp.Jobpost'),
        ),
        migrations.AddField(
            model_name='profile',
            name='removed_posts',
            field=models.ManyToManyField(blank=True, related_name='profile_users_removed', to='jobsapp.Jobpost'),
        ),
    ]
