# Generated by Django 2.2.5 on 2020-10-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200721_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='removed_count',
        ),
        migrations.AlterField(
            model_name='profile',
            name='applied_posts',
            field=models.ManyToManyField(blank=True, related_name='profile_applied', to='jobsapp.Jobpost'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='removed_posts',
            field=models.ManyToManyField(blank=True, related_name='profile_removed', to='jobsapp.Jobpost'),
        ),
    ]
