# Generated by Django 2.2.5 on 2020-07-03 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0004_jobpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='listparent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jobsapp.Joblist'),
        ),
    ]
