# Generated by Django 2.2.5 on 2020-07-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0006_jobpost_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='content',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='categories',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='company',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='description',
            field=models.CharField(default='test', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='position',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='url',
            field=models.CharField(default='test', max_length=1000),
            preserve_default=False,
        ),
    ]
