# Generated by Django 2.2.5 on 2020-07-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0007_auto_20200704_0103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joblist',
            old_name='query',
            new_name='desired_position',
        ),
        migrations.AddField(
            model_name='joblist',
            name='location',
            field=models.CharField(default='CA', max_length=50),
            preserve_default=False,
        ),
    ]
