# Generated by Django 2.2.5 on 2020-07-05 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0009_auto_20200705_0721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joblist',
            old_name='date_created',
            new_name='updated_date',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='updated_date',
        ),
    ]
