# Generated by Django 2.2.5 on 2020-07-05 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0010_auto_20200705_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='categories',
        ),
    ]
