# Generated by Django 2.2.5 on 2020-07-08 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0012_auto_20200705_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
