# Generated by Django 2.2.5 on 2020-07-08 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0013_jobpost_added_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='added_date',
            new_name='date_added',
        ),
    ]
