# Generated by Django 2.2.5 on 2020-07-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0016_auto_20200708_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='commitment',
            field=models.CharField(blank=True, default='_', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='company',
            field=models.CharField(blank=True, default='_', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='description',
            field=models.CharField(blank=True, default='_', max_length=1000),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='location',
            field=models.CharField(blank=True, default='_', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='position',
            field=models.CharField(blank=True, default='_', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='team',
            field=models.CharField(blank=True, default='_', max_length=100),
        ),
    ]
