# Generated by Django 2.2.5 on 2020-07-10 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobsapp', '0017_auto_20200709_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='owner',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='lever_id',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='owners',
            field=models.ManyToManyField(default='', to=settings.AUTH_USER_MODEL),
        ),
    ]
