# Generated by Django 2.2.5 on 2020-07-10 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0018_auto_20200710_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='listparent',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='listparents',
            field=models.ManyToManyField(default='', to='jobsapp.Joblist'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='owners',
            field=models.ManyToManyField(default='tarcher', to=settings.AUTH_USER_MODEL),
        ),
    ]
