# Generated by Django 2.2.5 on 2020-07-11 18:21

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobsapp', '0019_auto_20200710_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobquery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('location', models.CharField(default='', max_length=50)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('owners', models.ManyToManyField(default='', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='already_applied',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='listparents',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='owners',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='applied_users',
            field=models.ManyToManyField(default='', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Joblist',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='jobqueries',
            field=models.ManyToManyField(default='', to='jobsapp.Jobquery'),
        ),
    ]
