# Generated by Django 2.2.5 on 2020-07-12 01:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0020_auto_20200711_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='applied_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='description',
            field=models.CharField(blank=True, default='_', max_length=2000),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='jobqueries',
            field=models.ManyToManyField(blank=True, to='jobsapp.Jobquery'),
        ),
    ]
