# Generated by Django 2.2.5 on 2020-07-15 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0021_auto_20200712_0140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
