# Generated by Django 2.2.5 on 2020-07-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0022_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobquery',
            name='combined_query',
            field=models.CharField(default=' ', max_length=150),
            preserve_default=False,
        ),
    ]
