# Generated by Django 2.2.5 on 2020-07-17 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0023_jobquery_combined_query'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobquery',
            name='combined_query',
        ),
    ]
