# Generated by Django 2.2.5 on 2020-07-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0024_remove_jobquery_combined_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobquery',
            name='combined_query',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
