# Generated by Django 2.2.5 on 2020-07-18 14:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0025_jobquery_combined_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='queries_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='query_limit',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='jobquery',
            name='is_sample_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobquery',
            name='owners',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
