# Generated by Django 2.2.5 on 2020-07-18 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0026_auto_20200718_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='queries_today',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='query_limit',
        ),
    ]
