# Generated by Django 2.2.5 on 2020-07-21 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0027_auto_20200718_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='applied_users',
        ),
    ]
